Repository TicketSwap/php-kafka-consumer, pull requests merged in 2020-11, with the labels that each got.

#8 Tweaked consumer command shutdown speed
  composer.json
  src/Bundle/Command/KafkaConsumerCommand.php
  src/Consumer/KafkaConsumer.php
  src/Consumer/KafkaConsumerFactory.php
Labels: ready to merge

#9 Remove producer property from consumer instance
  src/Consumer/KafkaConsumerFactory.php
Labels: first approval, ready for review

#10 Update to rdkafka 4.0.4
  .github/workflows/php.yml
  composer.json
  composer.lock
Labels: ready for review

#11 Lazy load KafkaConsumer
  src/Bundle/Resources/config/services.yaml
Labels: first approval, ready for review

#13 Remove kernel environment for consumer
  src/Bundle/Command/KafkaConsumerCommand.php
  src/Bundle/Resources/config/services.yaml
  tests/Bundle/Command/KafkaConsumerCommandTest.php
Labels: first approval, ready for review
